### ISSUE TITLE
추천글 클릭 시 무한로딩

### ISSUE THREAD

**Issue by shirohoo** [tmkimm/hola#15]
![2](https://user-images.githubusercontent.com/71188307/129468674-9943e1f9-dcaa-4bff-bf29-340e28860234.JPG)

게시글 우측에 추천글이 뜹니다.

![1](https://user-images.githubusercontent.com/71188307/129468680-16f3713b-0172-470e-bea0-d93c43be7304.JPG)

글을 클릭하면 무한로딩이 걸립니다.

![image](https://user-images.githubusercontent.com/71188307/129468933-aba6549f-6f56-45a2-bc1e-a947a56cd0a8.png)

콘솔에 노출되는 로그를 남깁니다.

**Comment by tmkimm** [comment]
안녕하세요! 
무한 로딩 이슈 정상적으로 수정되었습니다.
버그 리포트 감사합니다 : )
